"""
Sea freight domain models for NZ port container operations.
海运货物领域模型 - 新西兰港口集装箱作业

The vessel schedule layer (VesselVisit) is sourced from PortConnect's real
New Zealand port data. Container cargo, tracking events and exceptions are
generated by the simulator against those real vessel visits.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from database import Base


class SeaPort(Base):
    """
    Port master data - NZ ports + international gateways.
    港口主数据
    """
    __tablename__ = "sea_ports"

    id = Column(Integer, primary_key=True, index=True)
    port_code = Column(String(5), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=False)
    city = Column(String(100), nullable=False)
    country = Column(String(100), nullable=False)
    is_nz_port = Column(Boolean, default=True)
    congestion_level = Column(Integer, default=2)  # 1-5 拥堵等级


class VesselVisit(Base):
    """
    Vessel visit / schedule record - sourced from PortConnect real data.
    船舶挂靠 / 船期 - 来自 PortConnect 真实数据
    """
    __tablename__ = "vessel_visits"

    id = Column(Integer, primary_key=True, index=True)
    vessel_visit_id = Column(String(60), unique=True, nullable=False, index=True)
    vessel_name = Column(String(100), nullable=False, index=True)
    imo_number = Column(String(10), nullable=True)
    inbound_voyage = Column(String(30), nullable=True)
    outbound_voyage = Column(String(30), nullable=True)
    vessel_status = Column(String(20), nullable=False)
    # 'EXPECTED', 'INPORT', 'DEPARTED', 'CANCELLED'
    vessel_type = Column(String(20), nullable=True)  # 'COMMERCIAL', 'CRUISE'
    port_code = Column(String(5), ForeignKey("sea_ports.port_code"), nullable=False)
    wharf_name = Column(String(100), nullable=True)
    berth = Column(String(20), nullable=True)
    previous_port = Column(String(100), nullable=True)
    next_port = Column(String(100), nullable=True)
    vessel_operator = Column(String(100), nullable=True)
    service_code = Column(String(60), nullable=True)
    arrival_datetime = Column(DateTime, nullable=True)
    departure_datetime = Column(DateTime, nullable=True)
    last_updated = Column(DateTime, nullable=True)
    # Derived: delay vs original schedule (minutes)
    delay_minutes = Column(Integer, default=0)
    delay_reason_code = Column(String(50), nullable=True)
    loaded_at = Column(DateTime, default=datetime.utcnow)

    port = relationship("SeaPort", foreign_keys=[port_code])
    containers = relationship("SeaContainer", back_populates="vessel")


class SeaContainer(Base):
    """
    Container record - the core sea freight shipment unit (generated cargo).
    集装箱记录 - 核心海运货物单元（自行生成）
    """
    __tablename__ = "sea_containers"

    id = Column(Integer, primary_key=True, index=True)
    container_number = Column(String(11), unique=True, nullable=False, index=True)  # ISO 6346
    vessel_visit_id = Column(String(60), ForeignKey("vessel_visits.vessel_visit_id"), nullable=False)
    direction = Column(String(10), nullable=False)  # 'import', 'export'
    size = Column(String(10), nullable=False)  # '20FT', '40FT', '40HC'
    container_type = Column(String(10), nullable=False)  # 'GP', 'RF', 'OT', 'FR', 'HC'
    gross_weight_kg = Column(Float, nullable=False)

    # Cargo details
    commodity_code = Column(String(20), nullable=True)  # HS code
    commodity_desc = Column(Text, nullable=False)
    shipper_name = Column(String(200), nullable=True)
    consignee_name = Column(String(200), nullable=True)
    customer_name = Column(String(200), nullable=False)
    customer_tier = Column(String(20), nullable=False)  # 'VIP', 'high', 'medium', 'low'
    declared_value_nzd = Column(Float, nullable=False)
    service_level = Column(String(20), nullable=True)  # 'priority', 'standard', 'economy'
    sla_tier = Column(String(20), nullable=True)  # 'priority', 'standard', 'economy'

    # Special handling
    temp_required_c = Column(Float, nullable=True)
    temp_min_c = Column(Float, nullable=True)
    temp_max_c = Column(Float, nullable=True)
    temp_excursion_alert = Column(Boolean, default=False)
    is_dg = Column(Boolean, default=False)  # 危险品
    dg_class = Column(String(10), nullable=True)
    un_number = Column(String(10), nullable=True)

    # Status & SLA
    current_status = Column(String(30), nullable=False, default='at_sea')
    # 'at_sea', 'discharged', 'customs_hold', 'available', 'gate_out', 'delivered'
    customs_cleared = Column(Boolean, default=False)
    biosecurity_cleared = Column(Boolean, default=False)
    scheduled_delivery = Column(DateTime, nullable=True)
    estimated_delivery = Column(DateTime, nullable=True)
    sla_deadline = Column(DateTime, nullable=True)
    sla_grace_deadline = Column(DateTime, nullable=True)  # 宽限截止
    is_sla_breached = Column(Boolean, default=False)  # 是否 SLA 违约
    breach_type = Column(String(20), nullable=True)  # 'excused' / 'unexcused'
    sla_penalty_nzd = Column(Float, nullable=True)  # 违约金（NZD）
    discharged_at = Column(DateTime, nullable=True)
    available_at = Column(DateTime, nullable=True)
    delivered_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    vessel = relationship("VesselVisit", back_populates="containers")
    events = relationship("SeaTrackingEvent", back_populates="container")
    exceptions = relationship("SeaException", back_populates="container")


class SeaTrackingEvent(Base):
    """
    Container tracking milestone events.
    集装箱追踪事件里程碑
    """
    __tablename__ = "sea_tracking_events"

    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(String(50), unique=True, nullable=False, index=True)
    container_number = Column(String(11), ForeignKey("sea_containers.container_number"), nullable=False, index=True)
    event_code = Column(String(10), nullable=False)
    # VAD 船舶到港, DIS 卸货, CHD 海关扣留, CHR 海关放行, BIO 生物安全检查,
    # AVC 可提取, GTO 出闸, DLV 送达, DLY 延误通告, TEMP 温度异常
    event_desc = Column(String(200), nullable=False)
    location = Column(String(5), nullable=True)  # port code
    timestamp = Column(DateTime, nullable=False)
    source = Column(String(50), nullable=False, default='portconnect')  # 'portconnect', 'tms', 'customs'
    reason_code = Column(String(50), nullable=True)
    message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    container = relationship("SeaContainer", back_populates="events")


class SeaException(Base):
    """
    Sea freight exception model aligned with the main exception engine.
    海运异常模型（与主异常引擎对齐）
    """
    __tablename__ = "sea_exceptions"

    id = Column(Integer, primary_key=True, index=True)
    exception_id = Column(String(50), unique=True, nullable=False, index=True)
    container_number = Column(String(11), ForeignKey("sea_containers.container_number"), nullable=False, index=True)
    exception_type = Column(String(50), nullable=False)
    # 'vessel_delay', 'customs_hold', 'biosecurity_hold', 'port_congestion',
    # 'temp_excursion', 'damage', 'misroute', 'dg_incident'
    severity = Column(String(20), nullable=False)  # 'low', 'medium', 'high', 'critical'
    risk_level = Column(String(20), nullable=False)  # 'low', 'medium', 'high'
    risk_score = Column(Integer, nullable=False)  # 0-100
    detected_at = Column(DateTime, nullable=False)
    root_cause = Column(Text, nullable=True)
    ai_diagnosis = Column(Text, nullable=True)
    ai_confidence = Column(Float, nullable=True)
    status = Column(String(50), nullable=False)
    # 'detected', 'diagnosed', 'pending_approval', 'resolved', 'escalated'
    requires_human_approval = Column(Boolean, default=False)
    recovery_options = Column(Text, nullable=True)  # JSON array
    delay_hours = Column(Float, default=0.0)
    # ML 语义分类结果（业务板块 + 置信度 + 复核决策）
    business_section = Column(String(50), nullable=True)  # 6 个业务板块之一
    classification_confidence = Column(Float, nullable=True)  # 语义分类置信度 margin
    classification_decision = Column(String(20), nullable=True)  # 'automatic' / 'human_review' / 'ood'
    ood_score = Column(Float, nullable=True)  # 分布外分数（越高越分布外）
    is_ood = Column(Boolean, default=False)  # 是否分布外（全新异常模式）
    anomaly_score = Column(Float, nullable=True)  # 预测性异常分数（dwell-time 偏离度）
    anomaly_reason = Column(String(100), nullable=True)  # 如 dwell_DIS_AVC_exceeded_p95
    exception_category = Column(String(50), nullable=True)  # 8 类权威异常分类
    root_cause_category = Column(String(50), nullable=True)  # 10 类根因类别
    predicted_downstream_impact = Column(Text, nullable=True)  # 预测下游影响（异常链）
    recovery_cost = Column(Float, nullable=True)  # 恢复成本（NZD）
    recommended_action = Column(String(50), nullable=True)  # AI 选中的最佳恢复行动
    recommendation_reason = Column(Text, nullable=True)  # 推荐理由
    sla_clock_paused = Column(Boolean, default=False)  # 客户义务未履行，SLA 时钟暂停
    pause_reason = Column(String(20), nullable=True)  # 暂停原因（CU-01~CU-10）
    resolved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    container = relationship("SeaContainer", back_populates="exceptions")
